development:
  adapter: postgresql
  encoding: unicode
  database: offenerrat_ms
  username: milafrerichs
  password: 
  host: localhost
  port: 5432

test:
  adapter: sqlite3
  database: db/offenerrat_test.sqlite3
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] %>
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] %>
  host: <%= ENV.fetch 'DB_1_PORT_5432_TCP_ADDR', 'localhost' %>
  port: <%= ENV.fetch 'DB_1_PORT_5432_TCP_PORT', '5432' %>
