development:
  adapter: postgresql
  encoding: unicode
  database: or
  username: or
  password: or
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d1ra3evdbl6p8t
  username: xcpvwbexusyjhj
  password: 1c0lGcBzli2sUkSh-yc_WjzyW6
  host: ec2-107-22-169-108.compute-1.amazonaws.com
  port: 5432
